USE onlinefood;
CREATE TABLE ITEMS(
    FID1 INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FOOD1 VARCHAR(20),
    FCATEGORY1 VARCHAR(20),
    FAMOUNT1 INT

);
CREATE TABLE detail(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(20),
    EMAIL VARCHAR(30),
    PASS VARCHAR(15)
);
CREATE TABLE CARTS(
      USERID INT,
      FID2 INT,
      FNAME2 VARCHAR(20),
      FTYPE2  VARCHAR(20),
      FAMOUNT2 FLOAT,
      FNUM INT
);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'BURGER1','BURGERS',150);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'BURGER2','BURGERS',100);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'PIZZA1','PIZZAS',200);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'PIZZA2','PIZZAS',250);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'DRINK1','DRINKS',100);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'DRINK2','DRINKS',170);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'NOODLE1','FASTFOOD',230);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'NOODLE2','FASTFOOD',130);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'DESSERT1','DESSERTS',220);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'DESSERT2','DESSERTS',250);
INSERT INTO ITEMS(FID1,FOOD1,FCATEGORY1,FAMOUNT1) VALUES(null,'DESSERT3','DESSERTS',170);




